plugins {
    id 'java'
    id 'io.quarkus'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-jsonb'
    implementation 'io.quarkus:quarkus-smallrye-jwt'
    implementation 'io.quarkiverse.jdbc:quarkus-jdbc-sqlite:3.0.10'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'org.xerial:sqlite-jdbc:3.36.0.3'  // Driver direto do SQLite
    implementation 'io.quarkus:quarkus-hibernate-orm-panache'
    implementation 'io.quarkus:quarkus-hibernate-orm'
    implementation 'io.quarkus:quarkus-resteasy-reactive'  // Fornece suporte REST básico
    implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'  // Para JSON com Jackson
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.1.0'
    testImplementation 'io.rest-assured:rest-assured'
    testImplementation 'org.mockito:mockito-core:5.5.0'
}

group 'com.ismoke'
version '1.0.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}

compileJava {
    options.encoding = 'UTF-8'
    options.compilerArgs << '-parameters'
}

compileTestJava {
    options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes(
                'Main-Class': 'io.quarkus.bootstrap.runner.QuarkusLauncher' // Classe principal para Quarkus
        )
    }
}

tasks.named('quarkusBuild') {
    finalizedBy(tasks.named('build'))
}
