# Configuração do Datasource SQLite
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:./database.db  # Define o caminho do arquivo do banco
quarkus.datasource.username=
quarkus.datasource.password=

# Configurações do Hibernate ORM
# quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.schema-generation=update
quarkus.hibernate-orm.log.sql=true                # Loga as queries SQL (opcional)
