name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Run Tests
        run: |
          ./gradlew clean test jacocoTestReport || echo "Tests or coverage failed, but report will be saved."

      - name: Show Coverage Path
        run:
         echo "build/reports/jacoco/test/html/index.html"

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Clona o histórico completo do repositório

      # Faz deploy no heroku
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku auth:token
          heroku git:remote -a ismoke
          git push https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/ismoke.git main
